### ISSUE TITLE
sau khi tampermonkey update pb mới thì bị lỗi tin nhắn

### ISSUE THREAD

**Issue by datlmhg** [t-rekttt/invisible_message#1]
trước khi tamper update thì vẫn bình thường nhưng sau khi update thì bị lỗi như này:
sau khi bật:
![image](https://user-images.githubusercontent.com/86174857/153020364-14357d28-49fc-4d08-9fc2-53ca2274631d.png)
sau khi tắt:
![image](https://user-images.githubusercontent.com/86174857/153020499-ef0e01cd-e456-41ad-b423-a8f082c0730c.png)

**Comment by t-rekttt** [comment]
Bạn đang dùng phiên bản nào của script nhỉ?
