### ISSUE TITLE
chức năng ẩn 1 phần tin nhắn không hoạt động nữa ạ :((

### ISSUE THREAD

**Issue by datlmhg** [t-rekttt/invisible_message#2]
![image](https://user-images.githubusercontent.com/86174857/213896949-cc7fc9ff-14c3-4925-884c-8528727b61e7.png)

**Comment by t-rekttt** [comment]
Bạn dùng script ở đâu nhỉ? Script ẩn 1 phần tin nhắn nằm ở https://github.com/t-rekttt/invisible_message/blob/hidden-between-text/invisibleMessage.user.js

**Comment by datlmhg** [comment]
> Bạn dùng script ở đâu nhỉ? Script ẩn 1 phần tin nhắn nằm ở https://github.com/t-rekttt/invisible_message/blob/hidden-between-text/invisibleMessage.user.js
![Chụp web_24-1-2023_92459_www facebook com](https://user-images.githubusercontent.com/86174857/214200220-cec36547-9678-4584-9bfb-b109051457e3.jpeg)
dạ link a mới gửi e dùng được rồi à, còn link cũ e dùng script ở link fb ấy ạ

**Comment by t-rekttt** [comment]
Link trong hướng dẫn sử dụng của mình cũng tương tự mà nhỉ?
![image](https://user-images.githubusercontent.com/9071846/214295825-e20a80ab-e0f1-48f7-a6e2-029cbe0c9201.png)

**Comment by datlmhg** [comment]
e cũng k rõ nữa, lúc e cài ở link fb thì pb vẫn 0.6, lúc vô link a gửi e bên github thì mới ra 0.10
